name: Reusable Deploy
on: 
  workflow_call: 
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: 'Result of the deployment'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: deploy
        run: echo "step-result=success" >> $GITHUB_OUTPUT